{{- if .Values.eksCluster }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: publish-availability-monitor-secrets
  namespace: default
spec:
  encryptedData:
{{ if .Values.encrypted }}{{ toYaml .Values.encrypted | indent 4 }}{{ end }}
{{- end }}
